-- 고전 명구 시드 (연관 문장 추천용 · 공용 도메인 원문)
INSERT INTO passages (passage, eum, source, chapter, modern_korean, english, keywords) VALUES
('學而時習之, 不亦說乎','학이시습지 불역열호','논어','학이(學而)','배우고 때때로 익히면, 어찌 기쁘지 않겠는가?','Is it not a pleasure to learn and to practise what you have learned at due times?','學 而 時 習 之 說 배움'),
('有朋自遠方來, 不亦樂乎','유붕자원방래 불역낙호','논어','학이(學而)','벗이 먼 곳에서 찾아오니, 어찌 즐겁지 않겠는가?','Is it not delightful to have friends coming from afar?','朋 遠 方 來 樂 벗'),
('人不知而不慍, 不亦君子乎','인부지이불온 불역군자호','논어','학이(學而)','남이 알아주지 않아도 성내지 않으니, 어찌 군자가 아니겠는가?','Is he not a gentleman who feels no resentment though others do not know him?','人 知 慍 君 子 수양'),
('溫故而知新, 可以爲師矣','온고이지신 가이위사의','논어','위정(爲政)','옛것을 익혀 새것을 알면, 남의 스승이 될 수 있다.','He who reviews the old so as to learn the new is fit to be a teacher.','溫 故 知 新 師 배움'),
('學而不思則罔, 思而不學則殆','학이불사즉망 사이불학즉태','논어','위정(爲政)','배우되 생각하지 않으면 막연하고, 생각하되 배우지 않으면 위태롭다.','Learning without thought is labour lost; thought without learning is perilous.','學 思 罔 殆 則 배움'),
('知之爲知之, 不知爲不知','지지위지지 부지위부지','논어','위정(爲政)','아는 것을 안다고 하고, 모르는 것을 모른다고 하라.','When you know a thing, hold that you know it; when you do not, allow that you do not.','知 之 爲 不 정직'),
('三人行, 必有我師焉','삼인행 필유아사언','논어','술이(述而)','세 사람이 함께 가면 반드시 그중에 내 스승이 있다.','When three walk together, there is surely one from whom I can learn.','三 人 行 師 焉 배움'),
('己所不欲, 勿施於人','기소불욕 물시어인','논어','안연(顔淵)','내가 원하지 않는 것을 남에게 시키지 말라.','Do not impose on others what you yourself do not desire.','己 所 不 欲 勿 施 於 人 仁'),
('君子和而不同, 小人同而不和','군자화이부동 소인동이불화','논어','자로(子路)','군자는 어울리되 같아지지 않고, 소인은 같아지되 어울리지 못한다.','The gentleman is harmonious but not conformist; the small man conformist but not harmonious.','君 子 和 同 小 人 군자'),
('過猶不及','과유불급','논어','선진(先進)','지나침은 미치지 못함과 같다.','To go beyond is as wrong as to fall short.','過 猶 不 及 중용'),
('欲速則不達','욕속즉부달','논어','자로(子路)','서둘러 하려 하면 이루지 못한다.','He who wishes for speed will not reach his goal.','欲 速 則 不 達 조급'),
('見賢思齊焉','견현사제언','논어','이인(里仁)','어진 이를 보면 그와 같아지기를 생각하라.','When you see a worthy man, think of equalling him.','見 賢 思 齊 焉 수양'),
('克己復禮爲仁','극기복례위인','논어','안연(顔淵)','자기를 이겨 예로 돌아가는 것이 인이다.','To subdue oneself and return to propriety is perfect virtue.','克 己 復 禮 爲 仁 수양'),
('朝聞道, 夕死可矣','조문도 석사가의','논어','이인(里仁)','아침에 도를 들으면, 저녁에 죽어도 좋다.','If I hear the Way in the morning, I could die content in the evening.','朝 聞 道 夕 死 可 矣 도'),
('不患人之不己知, 患不知人也','불환인지불기지 환부지인야','논어','학이(學而)','남이 나를 알아주지 않음을 걱정하지 말고, 내가 남을 알지 못함을 걱정하라.','Do not grieve that men do not know you; grieve that you do not know men.','患 人 知 己 也 수양'),
('性相近也, 習相遠也','성상근야 습상원야','논어','양화(陽貨)','타고난 성품은 서로 가깝고, 익힌 습관은 서로 멀다.','By nature men are near alike; by practice they grow wide apart.','性 習 相 近 遠 也 배움'),
('民惟邦本, 本固邦寧','민유방본 본고방녕','서경','오자지가(五子之歌)','백성이 나라의 근본이니, 근본이 굳으면 나라가 편안하다.','The people are the root of the state; when the root is firm, the state is at peace.','民 邦 本 固 寧 정치'),
('得道多助, 失道寡助','득도다조 실도과조','맹자','공손추(公孫丑)','도를 얻으면 돕는 이가 많고, 도를 잃으면 돕는 이가 적다.','He who has the Way finds many helpers; he who loses it finds few.','得 失 道 多 寡 助 정치'),
('天時不如地利, 地利不如人和','천시불여지리 지리불여인화','맹자','공손추(公孫丑)','하늘의 때는 땅의 이로움에 못 미치고, 땅의 이로움은 사람의 화합에 못 미친다.','Timeliness of Heaven is less than advantage of Earth; advantage of Earth is less than harmony among men.','天 時 地 利 人 和 如 정치'),
('富貴不能淫, 貧賤不能移','부귀불능음 빈천불능이','맹자','등문공(滕文公)','부귀도 그를 방탕하게 하지 못하고, 빈천도 그를 흔들지 못한다.','Riches cannot corrupt him, poverty cannot shake him.','富 貴 貧 賤 能 수양'),
('上善若水','상선약수','노자 도덕경','제8장','가장 좋은 것은 물과 같다.','The highest good is like water.','上 善 若 水 도가'),
('知人者智, 自知者明','지인자지 자지자명','노자 도덕경','제33장','남을 아는 것은 지혜요, 자기를 아는 것은 밝음이다.','To know others is wisdom; to know oneself is enlightenment.','知 人 者 智 自 明 수양'),
('大器晩成','대기만성','노자 도덕경','제41장','큰 그릇은 늦게 이루어진다.','A great vessel takes long to complete.','大 器 晩 成 재능'),
('千里之行, 始於足下','천리지행 시어족하','노자 도덕경','제64장','천 리 길도 발밑에서 시작된다.','A journey of a thousand li begins beneath one foot.','千 里 行 始 於 足 下 시작'),
('吾生也有涯, 而知也無涯','오생야유애 이지야무애','장자','양생주(養生主)','내 삶에는 끝이 있으나, 앎에는 끝이 없다.','My life has a limit, but knowledge has none.','生 知 有 無 涯 也 而 배움'),
('靑出於藍','청출어람','순자','권학(勸學)','푸른색은 쪽에서 나온다 - 제자가 스승을 넘어선다.','Indigo blue comes out of the indigo plant.','靑 出 於 藍 學 제자'),
('鋸木不折','거목부절','순자','권학(勸學)','톱질을 멈추지 않으면 나무는 반드시 잘린다 - 꾸준함의 힘.',NULL,'木 不 折 學 노력'),
('如切如磋, 如琢如磨','여절여차 여탁여마','시경','위풍(衛風)','자르는 듯 갈는 듯, 쪼는 듯 문지르는 듯.','As cut, as filed, as chiselled, as polished.','如 切 磋 琢 磨 수양'),
('他人有心, 予忖度之','타인유심 여촌탁지','시경','소아(小雅)','남에게 마음이 있으니, 내가 그것을 헤아린다.',NULL,'他 人 有 心 度 之 배려'),
('日就月將','일취월장','시경','주송(周頌)','날로 나아가고 달로 자란다.','Advancing by the day, growing by the month.','日 就 月 將 성장'),
('修身齊家治國平天下','수신제가치국평천하','대학','경(經)','몸을 닦고 집을 가지런히 하고 나라를 다스려 천하를 평안히 한다.','Cultivate the self, order the family, govern the state, bring peace to the world.','修 身 齊 家 治 國 平 天 下 수양'),
('物有本末, 事有終始','물유본말 사유종시','대학','경(經)','사물에는 근본과 말단이 있고, 일에는 끝과 시작이 있다.','Things have roots and branches; affairs have ends and beginnings.','物 有 本 末 事 終 始 순서'),
('喜怒哀樂之未發, 謂之中','희로애락지미발 위지중','중용','제1장','기쁨 노여움 슬픔 즐거움이 아직 드러나지 않은 상태를 중(中)이라 한다.',NULL,'喜 怒 哀 樂 未 發 中 중용'),
('博學之, 審問之, 愼思之','박학지 심문지 신사지','중용','제20장','널리 배우고, 자세히 묻고, 삼가 생각하라.','Study extensively, inquire carefully, think cautiously.','博 學 審 問 愼 思 之 배움'),
('生於憂患, 死於安樂','생어우환 사어안락','맹자','고자(告子)','근심과 걱정 속에서 살아나고, 편안함과 즐거움 속에서 죽는다.','Life springs from sorrow and calamity; death from ease and pleasure.','生 死 於 憂 患 安 樂 수양'),
('知彼知己, 百戰不殆','지피지기 백전불태','손자병법','모공(謀攻)','상대를 알고 나를 알면 백 번 싸워도 위태롭지 않다.','Know the enemy and know yourself, and you need not fear the result of a hundred battles.','知 彼 己 百 戰 不 殆 전략'),
('兵者, 詭道也','병자 궤도야','손자병법','계(計)','전쟁이란 속임의 길이다.','All warfare is based on deception.','兵 者 詭 道 也 전략'),
('先憂後樂','선우후락','악양루기','범중엄','먼저 근심하고 나중에 즐긴다.',NULL,'先 憂 後 樂 정치'),
('結草報恩','결초보은','좌전','선공(宣公)','풀을 묶어 은혜에 보답한다.',NULL,'結 草 報 恩 은혜'),
('唇亡齒寒','순망치한','좌전','희공(僖公)','입술이 없어지면 이가 시리다.','When the lips are gone, the teeth feel cold.','唇 亡 齒 寒 관계');
